#!/usr/bin/env bash

create() {
	echo "# $1"
	echo '```'
	grep -v '^#!/usr' "$2" | 
	grep -P '^#[ \t]*' -A 0 | 
	sed 's/^--$/ /' | 
	expand -t 4 | 
	sed -e 's/# /  /' -e 's/^#//' |
	sed -s 's/^[A-Z ]*:[ ]*$/```\n###&\n```/'
	echo '```'
}

create imp src/split_imp.sh > README.md
create map src/split_map.sh > README_map.md
create object src/split_object.sh > README_object.md
create imp_utils src/split_imp_utils.sh > README_imp_utils.md

